### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by rodritwm** [RealKoolisw/Draconian#145]
I have this problem when running the script:
ReferenceError: __dirname is not defined in ES module scope

**Comment by ckt1031** [comment]
@rodritwm can you show the full error logs for me to look through the parts where the error comes from.

**Comment by vadapadix** [comment]
> @rodritwm can you show the full error logs for me to look through the parts where the error comes from.

![image](https://user-images.githubusercontent.com/78354559/229583134-35f411ef-35d1-4849-8d8a-cceeefd23017.png)

**Comment by ckt1031** [comment]
This is fixed.
